#!/bin/bash
set -eo pipefail

pharod="$(command -v pharod)"
if [[ -z $pharod ]]; then
  echo "pharod not found in \$PATH, please check it's installed properly"
  exit 1
fi

if pgrep -qx pharod; then
  echo "You can only have one instance of pharod running at one time"
  exit 1
fi

sudo mkdir -p /etc/resolver

DOCKER_HOST_IP="localhost"
# We have to hard-code this because we have no SSH access to the VM:
DOCKER_FIRST_EPHEMERAL_PORT='32768'

args=""

if [[ -z $PHAROD_FOREGROUND ]]; then
  args="$args -d"
fi

exec sudo sh -c "DOCKER_HOST='unix:///var/run/docker.sock' DOCKER_HOST_IP='$DOCKER_HOST_IP' DOCKER_FIRST_EPHEMERAL_PORT='$DOCKER_FIRST_EPHEMERAL_PORT' '$pharod' $args"
